# backend/app/schemas/analysis_models.py
# Purpose: Define the strict data structures for the application using Pydantic.
# These schemas ensure type safety and clear data contracts between modules.

from pydantic import BaseModel, Field
from typing import List, Dict, Optional

# --- Input Models ---

class ResumeContent(BaseModel):
    """
    Structured content extracted from a resume.
    """
    raw_text: str
    skills: List[str] = Field(default_factory=list)
    experience: List[str] = Field(default_factory=list, description="List of experience descriptions")
    projects: List[str] = Field(default_factory=list, description="List of project descriptions")

class JobDescription(BaseModel):
    """
    Structured content for the target Job Description.
    """
    raw_text: str
    required_skills: List[str] = Field(default_factory=list)

# --- Rule Engine Output Models ---

class SkillAnalysis(BaseModel):
    """
    Result of the skill gap analysis.
    """
    strong_matches: List[str] = []
    weak_matches: List[str] = []
    missing_skills: List[str] = []

class ScoringResult(BaseModel):
    """
    Deterministic scores calculated by the Rule Engine.
    """
    overall_score: float
    skills_score: float
    experience_score: float
    project_score: float

class AnalysisComputations(BaseModel):
    """
    The complete output from the Rule Engine, BEFORE AI processing.
    """
    scores: ScoringResult
    skill_gap: SkillAnalysis
    resume_data: ResumeContent  # Included context for the AI
    jd_data: JobDescription     # Included context for the AI

# --- AI Output Models ---

class AIInsights(BaseModel):
    """
    Human-readable insights generated by the AI Brain.
    """
    summary_explanation: str
    ats_suggestions: List[str]
    rewritten_bullets: List[str]

# --- Final API Response ---

class FullAnalysisResponse(BaseModel):
    """
    The final response returned to the client.
    Combines Rule Engine data and AI Insights.
    """
    computation: AnalysisComputations
    ai_insights: AIInsights
